# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem 'awesome_print'
  gem 'pry'
  gem 'rubocop'
end

gem 'jwt'
gem 'mysql2'
gem 'rack-contrib'
gem 'sha3'
gem 'sinatra'
gem 'sinatra-contrib'
