---
- name: 'add k6 repo key'
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61

- name: 'add k6 repo'
  apt_repository:
    repo: deb https://dl.bintray.com/loadimpact/deb stable main
    update_cache: true
    validate_certs: false

- name: 'install essensial package'
  apt:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - mysql-client
      - redis-server
      - jq
      - k6
