FROM python:3.7.1

RUN apt-get update && apt-get install -y default-mysql-client
ARG project_dir=/app/
ARG app_dir=src/python
WORKDIR $project_dir

ADD $app_dir/requirements.txt $project_dir
RUN pip install -r requirements.txt

COPY common/init.sh $project_dir/scripts/init.sh
COPY db/init.sql $project_dir/scripts/init.sql

COPY $app_dir/ $project_dir
COPY public $project_dir/public

CMD ["./endpoint.sh"]

EXPOSE 5000
