---
- name: 'install python3.7'
  apt:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - python3.7
      - libpython3.7-dev
      - python3-pip
      - python3-mysql.connector
      - python3-mysqldb
