version: "3.3"
services:
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    image: dashboard
    ports:
      - 9292:9292
    depends_on:
      - db
      - redis
    command: ["./wait-for-it.sh", "-t", "0", "db:3306", "--", "bundle", "exec", "rackup", "-o", "0.0.0.0"]
